### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by crismon-wing** [Godofdrakes/barrows-potential#6]
The plugin appears to have stopped working, have tried reinstalling it and restarting runelite, none of it helped.

**Comment by Godofdrakes** [comment]
Are there any UI elements on your screen? Or is it just not displaying anything at all?

**Comment by Godofdrakes** [comment]
A screenshot of the plugin's current settings would help quickly diagnose issues as well

**Comment by Voiture-0** [comment]
It is also not working for me, here to help debug.
![image](https://github.com/user-attachments/assets/46d589c1-f9e4-47e5-b361-2f8047b1b387)

The UI is showing, but none of the monsters in the crypt are getting highlighted, and the monsters to kill is not showing in the UI.
![image](https://github.com/user-attachments/assets/fe2aad3a-2c03-4e31-8c5c-4d8b110f2464)

**Comment by Voiture-0** [comment]
I found this exception in my client logs. This is the only related message:
```2024-09-20 04:02:25 EDT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at client.getVarbitValue(client.java:17037)
	at client.getVarbitValue(client.java:61995)
	at com.barrowspotential.BarrowsPotentialPlugin.getCurrentPlan(BarrowsPotentialPlugin.java:178)
	at com.barrowspotential.BarrowsPotentialPlugin.updatePlan(BarrowsPotentialPlugin.java:218)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.la(client.java:11182)
	at client.bj(client.java)
	at ba.ov(ba.java:409)
	at ba.hi(ba.java)
	at ba.run(ba.java:5071)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Godofdrakes** [comment]
A nullptr exception in the getVarbitValue call? 🤔 

BarrowsPotentialPlugin.java:178 is:

```Java
int rewardPotential = client.getVarbitValue( Varbits.BARROWS_REWARD_POTENTIAL );
```

The client is injected by RL so I can't imagine it being null. I'm pretty sure Java would have stopped the call stack there if so.

Now that it's the weekend I've got some time to sink my teeth into this. I'm headed over to barrows now to see if I can get a better idea what's going on.

**Comment by Godofdrakes** [comment]
Was this a one-off or does this bug happen every time you do a run? I've done a handful of runs while keeping an eye on my own client log but I haven't had any luck reproducing the issue. Did you do anything specific, either in game or in the plugin settings, immediately before the issue occurred?

**Comment by Voiture-0** [comment]
Seems to be working now lol. I'm guessing restarting RuneLite fixes whatever issue this is.
![image](https://github.com/user-attachments/assets/f0083f23-0e6a-40c4-8cc6-4f0cbc1311ba)

**Comment by Voiture-0** [comment]
PS. I wasn't planning on doing more Barrows, but went to it to see if it was fixed. So I did a single run...
![image](https://github.com/user-attachments/assets/aa927691-da9f-4a3c-b13b-dd20398ef638)
worth it lol ty

**Comment by MalakaJones** [comment]
Just got the same issue this morning. Completly stopped working. I haven't tried to reinstall so far, but i'll keep you updated.

Here is the exception i get. This exception has been going on and off for days:

```
2024-10-15 09:36:50 EDT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.NullPointerException: null
	at client.getVarbitValue(client.java:61844)
	at client.getVarbitValue(client.java:37355)
	at com.barrowspotential.BarrowsPotentialPlugin.getCurrentPlan(BarrowsPotentialPlugin.java:178)
	at com.barrowspotential.BarrowsPotentialPlugin.updatePlan(BarrowsPotentialPlugin.java:218)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.oj(client.java:53660)
	at client.bj(client.java)
	at ba.aw(ba.java:409)
	at ba.ri(ba.java)
	at ba.run(ba.java:25527)
	at java.base/java.lang.Thread.run(Unknown Source)
```
In yesterday's log tho, it seems to have loaded properly, but then I got multiple warnings and then this morning nothing works.
```

2024-10-14 11:36:13 EDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "barrows-potential" jar "yjZ5KeKaOG2GeZqL3BKiQvyGCBKfiW8GARRqhVE2kLw"
2024-10-14 15:40:16 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:40:17 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:40:55 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:41:03 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:41:16 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:41:22 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:41:33 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:42:04 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:42:11 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:42:17 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:43:09 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:43:12 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:43:31 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:44:13 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:44:17 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:44:32 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:44:55 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:44:59 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
2024-10-14 15:45:12 EDT [Client] WARN  c.b.BarrowsPotentialPlugin - plan does not meet target
```
I attached yesterday and today's log if you need.
[client.log](https://github.com/user-attachments/files/17382496/client.log)
[client_2024-10-14.0.log](https://github.com/user-attachments/files/17382501/client_2024-10-14.0.log)

**Relauching Runelite fixed it and it did not throw an eception this time.**
[client.log](https://github.com/user-attachments/files/17382703/client.log)

**Comment by bowerscd** [comment]
This has happened to me as well; restarting runelite once did not help.

Curiously, it does appear to be machine specific, i have another device that this isn't reproducing for with the exact same account and runelite versions.

~~EDIT, also got a new error:~~

```log
2024-10-16 18:36:59 PDT [Client] ERROR n.r.client.callback.ClientThread - Exception in invoke
java.lang.IllegalArgumentException: Collection is empty
	at java.base/java.util.EnumSet.copyOf(Unknown Source)
	at com.barrowspotential.BarrowsPotentialPlugin.getConfigPlan(BarrowsPotentialPlugin.java:204)
	at com.barrowspotential.BarrowsPotentialPlugin.updatePlan(BarrowsPotentialPlugin.java:229)
	at net.runelite.client.callback.ClientThread.lambda$invokeLater$1(ClientThread.java:80)
	at net.runelite.client.callback.ClientThread.invokeList(ClientThread.java:119)
	at net.runelite.client.callback.ClientThread.invoke(ClientThread.java:101)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:226)
	at client.ac(client.java:12804)
	at client.bc(client.java)
	at bz.ab(bz.java:394)
	at bz.yu(bz.java)
	at bz.run(bz.java:18865)
	at java.base/java.lang.Thread.run(Unknown Source)
```

EDIT2: This is just me not selecting a "reward plan" - but curiously, i cannot select one as the setting doesn't stick; and more curiously, I didn't touch this setting.

EDIT3: Resetting the plugin's setting seems to have sorted it out.

**Comment by Godofdrakes** [comment]
The "Collection is empty" error looks like an easy fix. Simple mistake on my part not checking if the reward plan was empty before trying to copy it.

Thanks all for the logs. I'm cracking open the code again now. Hoping I can figure out what's going on.

**Comment by Godofdrakes** [comment]
I've got a fix for the `IllegalArgumentException` and a _tentative_ fix for the `NullPointerException`. I'll do a few rounds of barrows tomorrow to make sure nothing explodes and then get the plugin hub updated.

**Comment by Godofdrakes** [comment]
I've opened a pull request to update the plugin (https://github.com/runelite/plugin-hub/pull/6817). I'll update this issue again when the update is accepted.

**Comment by Godofdrakes** [comment]
The update has been accepted. I'll leave this issue open for a little while longer. Would love if someone who was hitting the exception could report back confirming if it's fixed for them or not.

**Comment by MalakaJones** [comment]
This is the last time i've seen the "NullPointerException".

`2024-10-19 09:33:40 EDT`

Looking good so far. Crossing fingers.

**Comment by MalakaJones** [comment]
Still no issues for the last 10 days.
